import "./globals.css";

import Header from "@/template/Header";
import localFont from "next/font/local";

const yekanFont = localFont({
  src: "../public/fonts/Yekan.woff2",
  display: "swapp",
});

export const metadata = {
  title: "تورینو",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={yekanFont.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
